### ISSUE TITLE
Add patient without passing NHS number for Type#1

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/integration-adaptor-nhais#126]
URL - http://localhost/fhir/Patient/$nhais.acceptance
Headers - Content-Type : application/json
Request Body -
{
"parameter": [
{
"name": "gpTradingPartnerCode",
"valueString": "TES5"
},
{
"name": "acceptanceCode",
"valueString": "A"
},
{
"name": "acceptanceType",
"valueString": "1"
},
{
"name": "acceptanceDate",
"valueString": "1992-01-13"
},
{
"name": "patient",
"resource": {
"managingOrganization": {
"identifier": [{
"system": "https://digital.nhs.uk/services/nhais/guide-to-nhais-gp-links-documentation",
"value": "XX1"
}]
},
"generalPractitioner": [
{
"identifier": {
"system": "https://fhir.hl7.org.uk/Id/gmc-number",
"value": "4826940,281"
}
}
],
"name": [
{
"family": "STEVENS"
}
],
"gender": "male",
"birthDate": "1991-11-06",
"address": [
{
"line": [
"MOORSIDE FARM",
"OLD LANE",
"ST PAULS CRAY",
"ORPINGTON",
"KENT"
],
"use": "home"
}
],
"resourceType": "Patient"
}
}
],
"resourceType": "Parameters"
}

Expected Response- 400 Bad Request
Actual Response- 202 The acceptance is forwarded to NHAIS for processing

**Comment by mattd-kainos** [comment]
To be fixed to NIAD-205 "Validate Acceptance API payload - Mandatory / Optional" in Sprint 11

**Comment by mattd-kainos** [comment]
Now scheduled for Sprint 12

**Comment by sonalnegivarma** [comment]
This issue is resolved in the latest docker image. We are getting expected response code with body. Test Data -
URL - http://localhost/fhir/Patient/$nhais.acceptance
Headers - Content-Type : application/json
Request Body -
{
  "parameter": [
    {
      "name": "gpTradingPartnerCode",
      "valueString": "TES5"
    },
    {
      "name": "acceptanceCode",
      "valueString": "A"
    },
    {
      "name": "acceptanceType",
      "valueString": "1"
    },
    {
      "name": "acceptanceDate",
      "valueString": "1992-01-13"
    },
    {
      "name": "freeText",
      "valueString": "GP NOTES GO HERE"
    },
    {
      "name": "patient",
      "resource": {
        "managingOrganization": {
          "identifier": [
            {
              "system": "https://digital.nhs.uk/services/nhais/guide-to-nhais-gp-links-documentation",
              "value": "XX1"
            }
          ]
        },
        "generalPractitioner": [
          {
            "identifier": {
              "system": "https://fhir.hl7.org.uk/Id/gmc-number",
              "value": "4826940,281"
            }
          }
        ],
        "name": [
          {
            "family": "STEVENS",
            "given": [
              "CHARLES",
              "ANTHONY",
              "JOHN"
            ],
            "prefix": [
              "MR"
            ]
          },
          {
            "family": "PREVIOUS"
          }
        ],
        "gender": "male",
        "birthDate": "1991-11-06",
        "address": [
          {
            "line": [
              "MOORSIDE FARM",
              "OLD LANE",
              "ST PAULS CRAY",
              "ORPINGTON",
              "KENT"
            ],
            "postalCode": "BR6  7EW"
          }
        ],
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueString": "BURY"
          },
          {
            "url": "https://fhir.nhs.uk/R4/StructureDefinition/Extension-UKCore-NHAIS-DrugsDispensedMarker",
            "valueBoolean": true
          },
          {
            "url": "https://fhir.nhs.uk/R4/StructureDefinition/Extension-UKCore-NHAIS-ResidentialInstituteCode",
            "valueString": "RT"
          }
        ],
        "resourceType": "Patient"
      }
    }
  ],
  "resourceType": "Parameters"
}
Expected Response- 400 Bad Request
Actual Response- 400 Bad Request
Response Body -
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "structure",
      "details": {
        "text": "**NHS number of patient is missing**"
      }
    }
  ]
}
