### ISSUE TITLE
Add patient without passing surname for Type#1, 2,3 and 4

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/integration-adaptor-nhais#127]
URL - http://localhost/fhir/Patient/$nhais.acceptance
Content-Type:  application/json
Request Body  - {
"parameter": [
{
"name": "gpTradingPartnerCode",
"valueString": "TES5"
},
{
"name": "acceptanceCode",
"valueString": "A"
},
{
"name": "acceptanceType",
"valueString": "1"
},
{
"name": "acceptanceDate",
"valueString": "1992-01-13"
},
{
"name": "patient",
"resource": {
"managingOrganization": {
"identifier": [{
"system": "https://digital.nhs.uk/services/nhais/guide-to-nhais-gp-links-documentation",
"value": "XX1"
}]
},
"generalPractitioner": [
{
"identifier": {
"system": "https://fhir.hl7.org.uk/Id/gmc-number",
"value": "4826940,281"
}
}
],
"identifier": [
{
"system": "https://fhir.nhs.uk/Id/nhs-number",
"value": "N/10/10"
}
],
"name": [
{
"family": null
}
],
"gender": "male",
"birthDate": "1991-11-06",
"address": [
{
"line": [
"MOORSIDE FARM",
"OLD LANE",
"ST PAULS CRAY",
"ORPINGTON",
"KENT"
],
"use": "home"
}
],
"resourceType": "Patient"
}
}
],
"resourceType": "Parameters"
}

Expected response- 400 Bad Request
Actual Response - 202 The acceptance is forwarded to NHAIS for processing

This issue is observed in all four types of acceptance transaction

**Comment by mattd-kainos** [comment]
To be fixed to NIAD-205 "Validate Acceptance API payload - Mandatory / Optional" in Sprint 11

**Comment by mattd-kainos** [comment]
Now scheduled for Sprint 12

**Comment by michael-kainos** [comment]
This is fixed and will be in the next release

**Comment by mattd-kainos** [comment]
Was fixed by https://github.com/nhsconnect/integration-adaptor-nhais/pull/216
