### ISSUE TITLE
Add patient without passing previous address for Type#3

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/integration-adaptor-nhais#128]
URL - http://localhost/fhir/Patient/$nhais.acceptance
Content- Type - application/json
Request Body - {
"parameter": [
{
"name": "gpTradingPartnerCode",
"valueString": "TES5"
},
{
"name": "acceptanceCode",
"valueString": "A"
},
{
"name": "acceptanceType",
"valueString": "3"
},
{
"name": "acceptanceDate",
"valueString": "1992-01-15"
},
{
"name": "previousGPName",
"valueString": "DR BLACK"
},
{
"name": "patient",
"resource": {
"managingOrganization": {
"identifier": [
{
"system": "https://digital.nhs.uk/services/nhais/guide-to-nhais-gp-links-documentation",
"value": "XX1"
}
]
},
"generalPractitioner": [
{
"identifier": {
"system": "https://fhir.hl7.org.uk/Id/gmc-number",
"value": "4826940,281"
}
}
],
"name": [
{
"family": "ASQUITH"
}
],
"gender": "male",
"address": [
{
"line": [
"THE MANSION HOUSE",
null,
"ST PAULS CRAY",
"ORPINGTON",
"KENT"
],
"use": "home"
},
{
"use": "old"
}
],
"extension": [
{
"url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
"valueString": "PETERBOROUGH"
},
{
"url": "https://fhir.nhs.uk/R4/StructureDefinition/Extension-UKCore-NHAIS-PreviousGP",
"valueString": "DR BLACK"
}
],
"resourceType": "Patient"
}
}
],
"resourceType": "Parameters"
}

Expected Response - 400 Bad Request
Actual Response - 202

**Comment by mattd-kainos** [comment]
To be fixed to NIAD-205 "Validate Acceptance API payload - Mandatory / Optional" in Sprint 11

**Comment by mattd-kainos** [comment]
Now scheduled for Sprint 12

**Comment by michael-kainos** [comment]
This has been fixed and will be in the next release

**Comment by mattd-kainos** [comment]
Fixed by https://github.com/nhsconnect/integration-adaptor-nhais/pull/229
