### ISSUE TITLE
Amend patient name with invalid path in request body

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/integration-adaptor-nhais#171]
URL -  PATCH: http://localhost/fhir/Patient/9999999999
Content -Type : Content-Type: application/json
Payload - {
  "nhsNumber": "9999999999",
  "gpCode": "2750922,295",
  "gpTradingPartnerCode": "TES5",
  "healthcarePartyCode": "XX1",
  "patches": [
    {
      "op": "add",
      **"path": "/name/0/prefix/name"**,
      "value": "abc"
    }
  ]
}

Expected Response - 400 
Actual Response - 202

**Comment by michael-kainos** [comment]
story raised in backlog - https://gpitbjss.atlassian.net/browse/NIAD-311 marked as a could as this is an unrealistic scenario and is unlikely to happen
Deferred
