### ISSUE TITLE
NHAIS_MESH_HOST must have a trailing slash in order to work

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#219]
This is a minor issue. 

Apparently, NHAIS_MESH_HOST variable currently must have a trailing slash at the end in order to work. 

suggestion
(1) should be captured in the documentation of the variable.
(2) or recoding to accept both with/without trailing slash.

**Comment by michael-kainos** [comment]
Will update the documentation to provide this information
