### ISSUE TITLE
Cannot consume amqp queue at port 5672 with .net client library

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#221]
* Description

I spent a couple of days sorting out the connectivity to activemq inbound queue via amqp protocol using .net client library (as our microservice using .net)

I am not able to successfully connect via amqp protocol, the server closes the connection straightaway. 
However,  I am able to connect via TCP protocol (port 61616) for openwire format, the message that comes back is amqp bytes array, which I found difficult to consume. 

One workaround is to modify the container with new config (activemq.xml) which modifying this line
<transportConnector name="amqp" uri="amqp://0.0.0.0:5672?transport.transformer=jms&amp;maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600"/>

Now the AMQP protocol has a JMS transformer, and now consuming queue via the OpenWire (via TCP=61616) format will return a text format for the body, the AMQP headers are still accessible just like normal. 

I just wonder if the container can be changed in this way to allow easy access for .net supplier. 
the file I changed is in the "integration-adaptor-nhais\activemq\activemq.xml"

* Component
NHAIS adaptor inbound

* Version
??

* Step to Reproduce
1. Configure to run e.g in Open test environment
2. Run testscript\1.1.0
3. Send Edifact message directly to the configured mailbox 
   (the message is taken from src\intTest\resource\inbound_uat_data
4. Wait until entries appears in the active MQ queue, under the name 'nahis_gp_system_inbound"
5. Run the client code using .net client library and connect to "amqp://ip:5672"
6. Result: client error when connecting with an indication the server force close the connection upon receiving connection request. 
  
*  Work around
1. go to activemq folder
2. open activemq.xml
3. modify this line and save the document

uri="amqp://0.0.0.0:5672?transport.transformer=jms&amp;maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600"

4. from the command shell , run
    docker build -t [dockerusername/activemq] .
    docker push [dockerusername/activemq]
5. in the docker-compose.yml, change from 'rmohr/activemq:latest' to [dockerusername/activemq]
   and open additional port  - "61616" : "61616"

6. .net client library can connect to 'tcp://[ip]:61616" instead of 'amqp://[ip]:5672'. 

   
   

* Preconditions
None

* Environment
None

* Severity
Low, as there is a workaround

* Priority
Not urgent

* Expected Behavior
.net Client application to be able to connect to ActiveMQ queue

**Comment by michael-kainos** [comment]
needs more information,please provide steps to reproduce, refer to the defect management process.
@Kusnaditjung

**Comment by mattd-kainos** [comment]
I don't see a reason for Kainos / NHDS to maintain a specific customisation of the activemq docker image for this use case. However you are free to do as you'd like to support your own application development needs.
