### ISSUE TITLE
Inbound and Outbound GPCode with system = 'https://fhir.hl7.org.uk/Id/gmc-number”

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#226]
The gpcode in Inbound and Outbound is a combination of GP GMC and GP Local Code, but the system is currently assigned to 'https://fhir.hl7.org.uk/Id/gmc-number'. This does not conform to the normal usage of the system value. see here for example https://developer.nhs.uk/apis/itk3tocedischarge/build_attachments.html.

 My suggestion will be either
(1) change to other custom system value, and explain the value format to be expected in the inbound and outbound.md
(2) or if option 1 is not a possibility, then it should still some documentation in the Inbound and Outbound.md about what the value format is expected for the NHAIS adapter

**Comment by mattd-kainos** [comment]
Is this a cosmetic improvement only or is the use of this identify system impacting your use of the adaptor in any way?

**Comment by Kusnaditjung** [comment]
I just highlight this, as inconsistent use 'system' (or OID system) within NHS national service, for example, https://fhir.nhs.uk/Id/nhs-number is used just for NHSNumber, and GMC system I thought should be used to convey just GMC code unless the GP Local code is part/extension of the GMC code. This is particularly because the system identifier is used elsewhere in the NHS National service.  It may be just because this is the first time I see the system code being used outside its original designation. I can be wrong, that is just my thought if you felt strongly about the decision, I am happy to adjust accordingly. The impact if we don't have documentation of this is: if the developer has been developing other NHS service with gmc system, and now working on this adapter, they will assume the value should be just 'GMC code' nor realising it should be "GMC code,GP Local Code'

**Comment by michael-kainos** [comment]
Hi @Kusnaditjung NHS have approved decisions taken on the adapter, any assumptions made by a new organisation integrating should only be around something without documentation. As this is defined in documentation i will close this issue
