### ISSUE TITLE
Deduction reason code

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#228]
For Outbound messaging page (specification\out\index.html), there is an enumeration for Deduction reason code in Deduction message, but only 3 option only,

(1) for deduction reason code for Deduction message in the Inbound message  page (INBOUND.md) does not have an enumeration note. I wonder whether they should be the same as the outbound or not. It will be clearer to put them down in the Inbound message page as well (or as links or any reference to outbound page)

(2) I found the test example in src/intTest/resources/inbound_uat_data/deduction/app-j-2.fhir.json has deduction reason code = 2 which is not in the Outbound message page. If this is true, that means the deduction reason code for outbound may be different compared to those of inbound.  So, either fixed the test example or improve the documentation for the deduction inbound message (for deduction reason code)

**Comment by mattd-kainos** [comment]
Refer to the GP Links specification chapter 3 for supported reason codes. Will update the documentation to also point in that direction.
