### ISSUE TITLE
NHAIS interaction is missing

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#231]
Since the purpose of the NHAIS adaptor is to enable the suppliers to implement NHAIS without looking at the original EDIFCAT documentation and MESH interaction, there should be some documentation for interaction between Inbound and Outbound messages, so that will be able to answer these questions:

(1) what are the inbound messages to be expected for a particular outbound message 
(2) what are the inbound messages that are not initiated by the GP System, and for what purposes? 

Expected: A diagram or table explaining outbound and inbound message interaction.

**Comment by mattd-kainos** [comment]
Chapter 3 of the GP Links specification has detailed descriptions including diagrams which answer these questions.

**Comment by mattd-kainos** [comment]
Closing this issue since these questions are answers by existing documentation and outside the scope of the adaptor.
