### ISSUE TITLE
Sequence number of local interchange not in sync with the GP Links

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/integration-adaptor-nhais#244]
Hi, I have communicated with NHS (Andrew.Guiseley@nhs.net), and they found the reason the message does not reply with approval is that it is considered as a duplicated message (sequence number is 2 in the below example). Apparently every time I re-deploy the adapter the number resets, so it is not in sync with the number recorded by the GP Links network. At the moment, we don't have control over the sequence number being sent to the GP Links. 

Here is the reply from him 

I’ve had another look in the Splunk logs, see below, looks like there was a duplicate sequence number issue

15/09/2020 11:07:39.637 Log_Level=WARN Process=gp_links_routing_w1 logReference=LNX0068 - Interchange sent a duplicate sequenceNumber=00000002 duplicateContent=True - internalID=20200915110739418653_6E7915_1573488313

15/09/2020 11:07:39.637 Log_Level=INFO Process=gp_links_routing_w1 logReference=LNX0065 - Duplicate Interchange with uid=SHQ5_GAT1_2_2_2 returned the matchingInterchanges=['20200904091446748760_914620_1573488313__INTERCHANGE'] - internalID=20200915110739418653_6E7915_1573488313

15/09/2020 11:07:39.637 Log_Level=WARN Process=gp_links_routing_w1 logReference=LNX1005 - Interchange rejection for sender=A88005GP001 recipient=5KFHC - error=['GP-LINKS-1009'] - internalID=20200915110739418653_6E7915_1573488313

**Comment by mattd-kainos** [comment]
This is likely caused by your deployment process deleting the database and/or its collections. The linked PR (https://github.com/nhsconnect/integration-adaptor-nhais/pull/247) now warns against this. The PR also adds instructions for "Linking a GP Practice to an NHAIS system" which you should follow to re-establish the GP/HA link.

**Comment by Kusnaditjung** [comment]
Thanks, that is most likely the case as we were currently doing a quick test, and do not persist the volume yet.  I just wonder if this can be implemented as a configuration feature (e.g SIS_Start, SMS_Start, TN_Start that will be used if there is no number yet in the db OR if the configuration numbers are greater than the ones in the db) as opposed to manually script this to mongo/cosmo, or alternatively providing a bash script that is ready to be run will be handy as well. Thank you.

**Comment by mattd-kainos** [comment]
It wouldn't make sense to do this with configuration because every GP/HA pair has its own sequence and therefore its own start.

**Comment by Kusnaditjung** [comment]
Ok, that makes sense.
