### ISSUE TITLE
Incorrect translation timestamp in RECEP message 

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/integration-adaptor-nhais#260]
When the RECEP message is generated. The translation timestamp is incorrect.
Attached are the screenshots for request send yesterday.
![image](https://user-images.githubusercontent.com/65003460/97266101-dd57cf80-184d-11eb-84b8-7b0ea2d42f54.png)

Expected Result -  Should be the timestamp when RECEP got generated

**Comment by mattd-kainos** [comment]
This is an issue with NHAIS and Release 1.4.0 contains a workaround for it. Correct dates are now reported.
