### ISSUE TITLE
NHAIS data received does not comply with validation requirements

### ISSUE THREAD

**Issue by davesmith9088** [NHSDigital/integration-adaptor-nhais#262]
According to the NHAIS specification (here: https://digital.nhs.uk/binaries/content/assets/website-assets/services/nhais/gp-spec-chapter3.doc), the Address - County field must "Have alphanumeric, SPACE, "'", "-", "." and "," characters only."  This means  "TYNE & WEAR" should not be allowed as ampersands are not included in the set of allowed characters, however we noticed that this appears in the test data.  When we sent registrations with "TYNE AND WEAR" as the county, we got back amendment messages to change the county to "TYNE & WEAR" which seems to contradict the specification.  

Please can we have this clarified, as we have implemented our validation to disallow the & character as per the spec.

**Comment by michael-kainos** [comment]
@davesmith9088 as discussed previously in the slack channel please see the reply below from the Hawthorne team. Based on this i will close this.

> Hawthorne Team:

> Sorry. This was a mistake on our part.
>  
> & is NOT a valid ‘GP Links EDIFACT Level A character set’ character. This was accidentally set up on our test machine and is not correct. We shall alter the data on Hawthorn now so that no further &s should be sent out.
>  
> Apologies for this. 
> 
>
